FROM nginx:trixie-perl

COPY index.html /usr/share/nginx/html/

EXPOSE 80

# docker build -t web <ruta de docker file>
# docker run --name test3 -p 4001:80 web
# docker start cont-web-2 cont-web-1
# docker stop cont-web-1 cont-web-2